// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GuidGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "GuidGenerator.2d82e3ee-2e03-4699-bcad-d5ad3c1bd095";
        public const string Name = "GuidGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jarryd Deane";
        public const string Tags = "";
    }
}
